import { deepFindObjKey, getCleanUrlVideo, wrapTryCatch } from '../common';
import type { TranscriptData, TranscriptTrackInfo } from '../interfaces/i_types';
import { buildInnertubeBody, buildInnertubeHeaders } from './request';
import { getInitYtData, getInnertubeApiKey, getPageCfgData, type InnertubeRequestParams } from './core';

async function findInitYParams(initData: [object]): Promise<string | undefined> {
    try {
        if (initData) {
            let param;
            for (const obj of initData) {
                const findObj = deepFindObjKey(obj, 'serializedShareEntity')[0];
                if (findObj) {
                    [, param] = (Object as any).entries(findObj)[0];
                }

                if (param) break;
            }
            return param;
        }
    } catch (e) {
        console.error(e);
        return undefined;
    }

    return undefined;
}

async function getParamsForTranscript(
    globalContext: Window & typeof globalThis,
    param: string,
    signal?: AbortSignal
): Promise<InnertubeRequestParams | undefined> {
    try {
        const ytcfgData = await getPageCfgData(globalContext, signal);
        const cleanUrl = getCleanUrlVideo(globalContext.location.href) ?? globalContext.location.href;

        if (!ytcfgData) {
            return undefined;
        }

        return {
            headers: buildInnertubeHeaders(ytcfgData, {
                'x-youtube-client-version': ytcfgData?.INNERTUBE_CONTEXT_CLIENT_VERSION || ''
            }),
            referrer: cleanUrl,
            referrerPolicy: 'origin-when-cross-origin',
            body: JSON.stringify(
                buildInnertubeBody({
                    ytcfgData,
                    params: param,
                    clientFallback: {}
                })
            ),
            method: 'POST',
            mode: 'cors',
            credentials: 'include'
        };
    } catch (e) {
        console.error(e);
        return undefined;
    }
}

function getTranscriptPot(): string | undefined {
    try {
        const visited = new WeakSet<object>();
        const urls: string[] = [];

        const walk = (obj: unknown): void => {
            if (!obj || typeof obj !== 'object') return;
            if (visited.has(obj as object)) return;
            visited.add(obj as object);
            for (const key in obj as any) {
                if (!Object.prototype.hasOwnProperty.call(obj, key)) continue;
                try {
                    const value: any = (obj as any)[key];
                    if (typeof value === 'string' && value.includes('pot=')) {
                        urls.push(value);
                    } else if (value && typeof value === 'object') {
                        walk(value);
                    }
                } catch {
                    continue;
                }
            }
        };

        walk(window as any);
        if (urls.length === 0) return undefined;
        const buf = new URL(urls[0]).searchParams.get('pot');
        return buf ? encodeURIComponent(buf) : undefined;
    } catch (e) {
        console.error(e);
        return undefined;
    }
}

function parseCaptionTracks(captions: any | undefined): TranscriptTrackInfo[] {
    if (!captions) return [];

    const tracks: TranscriptTrackInfo[] = [];

    const captionTracks: any[] = Array.isArray(captions.captionTracks) ? captions.captionTracks : [];
    for (const track of captionTracks) {
        const languageCode = track?.languageCode as string | undefined;
        if (!languageCode) continue;
        tracks.push({
            languageCode,
            displayName:
                track?.name?.simpleText || track?.name?.runs?.map((run: any) => run?.text).join('') || undefined,
            isAutoGenerated: track?.kind === 'asr',
            baseUrl: typeof track?.baseUrl === 'string' ? track.baseUrl : undefined,
            vssId: track?.vssId,
            kind: track?.kind,
            trackName: track?.trackName
        });
    }

    const audioTracks: any[] = Array.isArray(captions.audioTracks) ? captions.audioTracks : [];
    for (const audioTrack of audioTracks) {
        const captionTrackIndices: number[] = Array.isArray(audioTrack?.captionTrackIndices)
            ? audioTrack.captionTrackIndices
            : [];
        for (const index of captionTrackIndices) {
            const track = captionTracks[index];
            const languageCode = track?.languageCode as string | undefined;
            if (!languageCode) continue;
            if (!tracks.find((existing) => existing.languageCode === languageCode)) {
                tracks.push({
                    languageCode,
                    displayName:
                        track?.name?.simpleText ||
                        track?.name?.runs?.map((run: any) => run?.text).join('') ||
                        undefined,
                    isAutoGenerated: track?.kind === 'asr',
                    baseUrl: typeof track?.baseUrl === 'string' ? track.baseUrl : undefined,
                    vssId: track?.vssId,
                    kind: track?.kind,
                    trackName: track?.trackName
                });
            }
        }
    }

    return tracks;
}

async function getTranscriptTrackInfo(
    globalContext: Window,
    signal: AbortSignal
): Promise<{ tracks: TranscriptTrackInfo[]; defaultTrack?: TranscriptTrackInfo } | undefined> {
    const baseUrl = getCleanUrlVideo(globalContext.location.href) as string;
    const htmlResp = await fetch(baseUrl, {
        method: 'GET',
        mode: 'no-cors' as RequestMode,
        credentials: 'include',
        signal,
        cache: 'no-store'
    } as RequestInit);
    const html = await htmlResp.text();
    const splitted = html.split('"captions":');
    if (splitted.length <= 1) throw new Error('Fail to load video html');
    const captions = JSON.parse(
        splitted[1].split(',"videoDetails')[0].replace('\n', '')
    ).playerCaptionsTracklistRenderer;

    const tracks = parseCaptionTracks(captions);

    let defaultTrack: TranscriptTrackInfo | undefined;
    const captionTracks: any[] = Array.isArray(captions?.captionTracks) ? captions.captionTracks : [];

    // First, check if there's a direct defaultCaptionTrackIndex at root level
    const defaultCaptionIndex =
        typeof captions?.defaultCaptionTrackIndex === 'number' ? captions.defaultCaptionTrackIndex : undefined;

    if (typeof defaultCaptionIndex === 'number' && captionTracks[defaultCaptionIndex]) {
        const defaultCaption = captionTracks[defaultCaptionIndex];
        defaultTrack = tracks.find((track) => track.languageCode === defaultCaption?.languageCode);
    }

    // If no direct default, check the default audio track's defaultCaptionTrackIndex
    if (!defaultTrack && typeof captions?.defaultAudioTrackIndex === 'number') {
        const defaultAudioTrack = Array.isArray(captions?.audioTracks)
            ? captions.audioTracks[captions.defaultAudioTrackIndex]
            : undefined;

        // Use the audio track's defaultCaptionTrackIndex, not the first caption index
        const audioDefaultCaptionIndex =
            typeof defaultAudioTrack?.defaultCaptionTrackIndex === 'number'
                ? defaultAudioTrack.defaultCaptionTrackIndex
                : undefined;

        if (typeof audioDefaultCaptionIndex === 'number' && captionTracks[audioDefaultCaptionIndex]) {
            const defaultCaption = captionTracks[audioDefaultCaptionIndex];
            defaultTrack = tracks.find((track) => track.languageCode === defaultCaption?.languageCode);
        }
    }

    return {
        tracks,
        defaultTrack: defaultTrack || tracks[0]
    };
}

function buildTranscriptFromTimedText(xmlText: string): object | undefined {
    try {
        const parser = new DOMParser();
        const doc = parser.parseFromString(xmlText, 'application/xml');
        const nodes = Array.from(doc.getElementsByTagName('text')) as Element[];
        const entries: any[] = nodes.map((n) => ({
            start: parseFloat(n.getAttribute('start') || '0'),
            duration: parseFloat(n.getAttribute('dur') || '0'),
            text: n.textContent || ''
        }));
        const cueGroups = entries.map(({ text, start }) => ({
            transcriptCueGroupRenderer: {
                formattedStartOffset: { simpleText: toFormatted(start) },
                cues: [{ transcriptCueRenderer: { startOffsetMs: start * 1000, cue: { simpleText: text } } }]
            }
        }));
        return {
            actions: [
                {
                    updateEngagementPanelAction: {
                        content: {
                            transcriptRenderer: {
                                body: {
                                    transcriptBodyRenderer: { cueGroups }
                                }
                            }
                        }
                    }
                }
            ]
        };
    } catch (e) {
        console.error(e);
        try {
            const entries: any[] = [];
            const regex = /<text start="([0-9.]+)" dur="([0-9.]+)">([\s\S]*?)<\/text>/g;
            let m: RegExpExecArray | null;
            while ((m = regex.exec(xmlText))) {
                const start = parseFloat(m[1]);
                const text = m[3].replace(/<\/?\w+[^>]*>/g, '');
                entries.push({ start, text });
            }
            const cueGroups = entries.map(({ text, start }) => ({
                transcriptCueGroupRenderer: {
                    formattedStartOffset: { simpleText: toFormatted(start) },
                    cues: [{ transcriptCueRenderer: { startOffsetMs: start * 1000, cue: { simpleText: text } } }]
                }
            }));
            return {
                actions: [
                    {
                        updateEngagementPanelAction: {
                            content: {
                                transcriptRenderer: {
                                    body: { transcriptBodyRenderer: { cueGroups } }
                                }
                            }
                        }
                    }
                ]
            };
        } catch {
            return undefined;
        }
    }
}

function toFormatted(sec: number): string {
    try {
        let left = sec;
        const h = Math.floor(left / 3600);
        left -= h * 3600;
        const m = Math.floor(left / 60);
        left -= m * 60;
        const s = Math.floor(left);

        let output = `${s}`.padStart(2, '0');

        if (m || h) {
            let seg: string;

            if (!m) {
                seg = '00';
            } else {
                if (h) {
                    seg = `${m}`.padStart(2, '0');
                } else {
                    seg = m.toString();
                }
            }

            output = `${seg}:${output}`;
        }

        if (h) {
            output = `${h}:${output}`;
        }

        if (!m && !h) {
            output = `0:${output}`;
        }

        return output;
    } catch {
        return '0:00';
    }
}

export async function getTranscriptTracks(signal: AbortSignal): Promise<TranscriptTrackInfo[] | undefined> {
    try {
        const info = await getTranscriptTrackInfo(window, signal);
        return info?.tracks;
    } catch (e) {
        console.error(e);
        return undefined;
    }
}

function selectTranscriptTrack(
    tracks: TranscriptTrackInfo[] | undefined,
    preferredLanguage?: string,
    fallbackTrack?: TranscriptTrackInfo
): TranscriptTrackInfo | undefined {
    if (!tracks || tracks.length === 0) return undefined;
    if (preferredLanguage) {
        const normalizedPreferred = preferredLanguage.toLowerCase();
        const exact = tracks.find((track) => track.languageCode?.toLowerCase() === normalizedPreferred);
        if (exact) return exact;
    }

    if (fallbackTrack) {
        return fallbackTrack;
    }

    const englishTrack = tracks.find((track) => track.languageCode?.toLowerCase().startsWith('en'));
    if (englishTrack) return englishTrack;

    const autoGenerated = tracks.find((track) => track.isAutoGenerated);
    if (autoGenerated) return autoGenerated;

    return tracks[0];
}

async function fetchTranscriptFromTimedText(baseUrl: string, signal: AbortSignal): Promise<TranscriptData | undefined> {
    const viaTimedText = await fetch(baseUrl, {
        method: 'GET',
        mode: 'no-cors' as RequestMode,
        credentials: 'include',
        signal,
        cache: 'no-store'
    } as RequestInit);
    const text = await viaTimedText.text();
    return buildTranscriptFromTimedText(text) as TranscriptData | undefined;
}

export async function getTranscriptVideo(
    signal: AbortSignal,
    options?: { languageCode?: string }
): Promise<TranscriptData | undefined> {
    try {
        const initData = await getInitYtData(getCleanUrlVideo(window.location.href) as any, signal);

        try {
            if (initData) {
                const ytInitParam = await findInitYParams(initData);
                if (ytInitParam) {
                    const params = await getParamsForTranscript(window, ytInitParam, signal);
                    if (!params) {
                        throw new Error('Missing innertube params for transcript request');
                    }
                    if (options?.languageCode && params?.body) {
                        try {
                            const body = typeof params.body === 'string' ? JSON.parse(params.body) : {};
                            body.params = undefined;
                            body.captionParams = options.languageCode;
                            params.body = JSON.stringify(body);
                        } catch (err) {
                            console.warn('Failed to inject language into youtubei body', err);
                        }
                    }

                    if (params) {
                        const requestInit: RequestInit = {
                            ...params,
                            signal,
                            cache: 'no-store'
                        };

                        if (requestInit.body === undefined) {
                            requestInit.body = params.body;
                        }

                        const resp = await fetch(
                            `https://www.youtube.com/youtubei/v1/get_transcript?key=${getInnertubeApiKey()}`,
                            requestInit
                        );
                        const json = (await resp.json()) as TranscriptData;
                        const hasTranscript = wrapTryCatch(() =>
                            Boolean(
                                json.actions?.[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.body
                                    ?.transcriptBodyRenderer?.cueGroups?.length
                            )
                        );
                        if (hasTranscript) return json;
                    }
                }
            }
        } catch (e) {
            console.error('youtubei get_transcript attempt failed', e);
        }

        const info = await getTranscriptTrackInfo(window, signal);
        const tracks: TranscriptTrackInfo[] = info?.tracks ?? [];
        const selectedTrack = selectTranscriptTrack(tracks, options?.languageCode, info?.defaultTrack);
        const trackBaseUrl = selectedTrack?.baseUrl;

        if (trackBaseUrl) {
            try {
                const built = await fetchTranscriptFromTimedText(trackBaseUrl, signal);
                const ok = wrapTryCatch(() =>
                    Boolean(
                        built?.actions?.[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.body
                            ?.transcriptBodyRenderer?.cueGroups?.length
                    )
                );
                if (ok) {
                    return built;
                }
            } catch (err) {
                console.error('direct timedtext fallback failed', err);
            }

            const pot = getTranscriptPot();
            if (pot && trackBaseUrl) {
                try {
                    const viaTimedText = await fetch(`${trackBaseUrl}&potc=1&pot=${pot}&c=WEB`, {
                        method: 'GET',
                        mode: 'no-cors' as RequestMode,
                        credentials: 'include',
                        signal,
                        cache: 'no-store'
                    } as RequestInit);
                    const text = await viaTimedText.text();
                    const built = buildTranscriptFromTimedText(text) as TranscriptData | undefined;
                    if (built) return built;
                } catch (err) {
                    console.error('timedtext with pot failed', err);
                }
            }
        }
    } catch (e) {
        console.error(e);
        return undefined;
    }

    return undefined;
}
