import { getVideoId, wrapTryCatch } from '../common';
import type { TranscriptCueGroup, TranscriptData, TranscriptTrackInfo } from '../interfaces/i_types';
import { buildInnertubeBody } from './request';
import { getInnertubeApiKey, getPageCfgData } from './core';
import { buildSapSidAuthorizationHeader } from './authHeaders';
import { ANDROID_CLIENT_FALLBACK, WEB_CLIENT_FALLBACK } from './fallbacks';

function getTranscriptPot(): string | undefined {
    try {
        const visited = new WeakSet<object>();
        const urls: string[] = [];

        const walk = (obj: unknown): void => {
            if (!obj || typeof obj !== 'object') return;
            if (visited.has(obj as object)) return;
            visited.add(obj as object);
            for (const key in obj as any) {
                if (!Object.prototype.hasOwnProperty.call(obj, key)) continue;
                try {
                    const value: any = (obj as any)[key];
                    if (typeof value === 'string' && value.includes('pot=')) {
                        urls.push(value);
                    } else if (value && typeof value === 'object') {
                        walk(value);
                    }
                } catch {
                    continue;
                }
            }
        };

        walk(window as any);
        if (urls.length === 0) return undefined;
        const buf = new URL(urls[0]).searchParams.get('pot');
        return buf ? encodeURIComponent(buf) : undefined;
    } catch (e) {
        console.error(e);
        return undefined;
    }
}

function parseCaptionTracks(captions: any | undefined): TranscriptTrackInfo[] {
    if (!captions) return [];

    const tracks: TranscriptTrackInfo[] = [];

    const captionTracks: any[] = Array.isArray(captions.captionTracks) ? captions.captionTracks : [];
    for (const track of captionTracks) {
        const languageCode = track?.languageCode as string | undefined;
        if (!languageCode) continue;
        tracks.push({
            languageCode,
            displayName:
                track?.name?.simpleText || track?.name?.runs?.map((run: any) => run?.text).join('') || undefined,
            isAutoGenerated: track?.kind === 'asr',
            baseUrl: typeof track?.baseUrl === 'string' ? track.baseUrl : undefined,
            vssId: track?.vssId,
            kind: track?.kind,
            trackName: track?.trackName
        });
    }

    const audioTracks: any[] = Array.isArray(captions.audioTracks) ? captions.audioTracks : [];
    for (const audioTrack of audioTracks) {
        const captionTrackIndices: number[] = Array.isArray(audioTrack?.captionTrackIndices)
            ? audioTrack.captionTrackIndices
            : [];
        for (const index of captionTrackIndices) {
            const track = captionTracks[index];
            const languageCode = track?.languageCode as string | undefined;
            if (!languageCode) continue;
            if (!tracks.find((existing) => existing.languageCode === languageCode)) {
                tracks.push({
                    languageCode,
                    displayName:
                        track?.name?.simpleText ||
                        track?.name?.runs?.map((run: any) => run?.text).join('') ||
                        undefined,
                    isAutoGenerated: track?.kind === 'asr',
                    baseUrl: typeof track?.baseUrl === 'string' ? track.baseUrl : undefined,
                    vssId: track?.vssId,
                    kind: track?.kind,
                    trackName: track?.trackName
                });
            }
        }
    }

    return tracks;
}

/**
 * Resolve the player's default caption track. Order: root defaultCaptionTrackIndex,
 * default audio track's defaultCaptionTrackIndex, default audio track's first
 * captionTrackIndices entry (multi-language ASR videos expose only this), then tracks[0].
 * Matches by vssId so a manual and an asr track sharing a languageCode are not confused.
 */
export function resolveDefaultTranscriptTrack(
    captions: any | undefined,
    tracks: TranscriptTrackInfo[]
): TranscriptTrackInfo | undefined {
    const captionTracks: any[] = Array.isArray(captions?.captionTracks) ? captions.captionTracks : [];
    const defaultAudioTrack =
        typeof captions?.defaultAudioTrackIndex === 'number' && Array.isArray(captions?.audioTracks)
            ? captions.audioTracks[captions.defaultAudioTrackIndex]
            : undefined;

    const candidateIndices = [
        captions?.defaultCaptionTrackIndex,
        defaultAudioTrack?.defaultCaptionTrackIndex,
        Array.isArray(defaultAudioTrack?.captionTrackIndices) ? defaultAudioTrack.captionTrackIndices[0] : undefined
    ];

    for (const index of candidateIndices) {
        if (typeof index !== 'number') continue;
        const caption = captionTracks[index];
        if (!caption) continue;
        const match = caption.vssId
            ? tracks.find((track) => track.vssId === caption.vssId)
            : tracks.find((track) => track.languageCode === caption.languageCode);
        if (match) return match;
    }

    return tracks[0];
}

async function getTranscriptTrackInfo(
    globalContext: Window & typeof globalThis,
    signal: AbortSignal
): Promise<{ tracks: TranscriptTrackInfo[]; defaultTrack?: TranscriptTrackInfo } | undefined> {
    const baseUrl = `https://www.youtube.com/youtubei/v1/player?key=${getInnertubeApiKey()}`;
    const videoId = getVideoId(globalContext.location.href);
    if (!videoId) {
        return undefined;
    }
    const pageCfgData = await getPageCfgData(globalContext, signal);
    const ytcfgClient = pageCfgData?.INNERTUBE_CONTEXT?.client as Record<string, unknown> | undefined;

    const navigatorLang = globalContext.navigator?.language;
    const langParts = navigatorLang?.split('-') || [];
    const lastPart = langParts[langParts.length - 1];
    const navigatorRegion = lastPart?.length === 2 && lastPart === lastPart.toUpperCase() ? lastPart : undefined;

    const hl = (ytcfgClient?.hl as string) || navigatorLang || 'en';
    const gl = (ytcfgClient?.gl as string) || navigatorRegion || 'US';

    // Primary: ANDROID client (works for most videos without auth)
    let captions: any;
    try {
        const res = await fetch(baseUrl, {
            method: 'POST',
            mode: 'no-cors' as RequestMode,
            credentials: 'include',
            signal,
            cache: 'no-store',
            body: JSON.stringify(
                buildInnertubeBody({
                    ytcfgData: undefined,
                    videoId,
                    clientOverride: { ...ANDROID_CLIENT_FALLBACK, hl, gl },
                    extra: { racyCheckOk: true, contentCheckOk: true }
                })
            )
        } as RequestInit);
        const json = await res.json();
        captions = json?.captions?.playerCaptionsTracklistRenderer;
    } catch (e: unknown) {
        // Rethrow abort errors to respect cancellation
        if (e instanceof DOMException && e.name === 'AbortError') throw e;
        // ANDROID client failed, will try WEB fallback below
    }

    // Fallback: WEB client with auth (for age-restricted videos)
    if (!captions) {
        try {
            const authHeader = buildSapSidAuthorizationHeader({ context: globalContext });
            const headers: Record<string, string> = {
                'content-type': 'application/json'
            };
            if (authHeader) {
                headers.authorization = authHeader;
            }

            const webRes = await fetch(baseUrl, {
                method: 'POST',
                mode: 'cors' as RequestMode,
                credentials: 'include',
                headers,
                signal,
                cache: 'no-store',
                body: JSON.stringify(
                    buildInnertubeBody({
                        ytcfgData: undefined,
                        videoId,
                        clientOverride: {
                            clientName: WEB_CLIENT_FALLBACK.clientName,
                            clientVersion:
                                pageCfgData?.INNERTUBE_CONTEXT_CLIENT_VERSION || WEB_CLIENT_FALLBACK.clientVersion,
                            hl,
                            gl
                        },
                        extra: { racyCheckOk: true, contentCheckOk: true }
                    })
                )
            } as RequestInit);
            if (webRes.ok) {
                const webJson = await webRes.json();
                captions = webJson?.captions?.playerCaptionsTracklistRenderer;
            }
        } catch (e: unknown) {
            if (e instanceof DOMException && e.name === 'AbortError') throw e;
            // WEB fallback also failed, captions remains undefined
        }
    }

    const tracks = parseCaptionTracks(captions);

    return {
        tracks,
        defaultTrack: resolveDefaultTranscriptTrack(captions, tracks)
    };
}

function buildTranscriptFromTimedText(xmlText: string): object | undefined {
    try {
        const parser = new DOMParser();
        const doc = parser.parseFromString(xmlText, 'application/xml');
        const nodes = Array.from(doc.getElementsByTagName('text')) as Element[];
        const entries: any[] = nodes.map((n) => ({
            start: parseFloat(n.getAttribute('start') || '0'),
            duration: parseFloat(n.getAttribute('dur') || '0'),
            text: n.textContent || ''
        }));
        const cueGroups = entries.map(({ text, start, duration }) => ({
            transcriptCueGroupRenderer: {
                formattedStartOffset: { simpleText: toFormatted(start) },
                cues: [
                    {
                        transcriptCueRenderer: {
                            startOffsetMs: start * 1000,
                            durationMs: duration * 1000,
                            cue: { simpleText: text }
                        }
                    }
                ]
            }
        }));
        return {
            actions: [
                {
                    updateEngagementPanelAction: {
                        content: {
                            transcriptRenderer: {
                                body: {
                                    transcriptBodyRenderer: { cueGroups }
                                }
                            }
                        }
                    }
                }
            ]
        };
    } catch (e) {
        console.error(e);
        try {
            const entries: any[] = [];
            const regex = /<text start="([0-9.]+)" dur="([0-9.]+)">([\s\S]*?)<\/text>/g;
            let m: RegExpExecArray | null;
            while ((m = regex.exec(xmlText))) {
                const start = parseFloat(m[1]);
                const duration = parseFloat(m[2]);
                const text = m[3].replace(/<\/?\w+[^>]*>/g, '');
                entries.push({ start, duration, text });
            }
            const cueGroups = entries.map(({ text, start, duration }) => ({
                transcriptCueGroupRenderer: {
                    formattedStartOffset: { simpleText: toFormatted(start) },
                    cues: [
                        {
                            transcriptCueRenderer: {
                                startOffsetMs: start * 1000,
                                durationMs: duration * 1000,
                                cue: { simpleText: text }
                            }
                        }
                    ]
                }
            }));
            return {
                actions: [
                    {
                        updateEngagementPanelAction: {
                            content: {
                                transcriptRenderer: {
                                    body: { transcriptBodyRenderer: { cueGroups } }
                                }
                            }
                        }
                    }
                ]
            };
        } catch {
            return undefined;
        }
    }
}

function toFormatted(sec: number): string {
    try {
        let left = sec;
        const h = Math.floor(left / 3600);
        left -= h * 3600;
        const m = Math.floor(left / 60);
        left -= m * 60;
        const s = Math.floor(left);

        let output = `${s}`.padStart(2, '0');

        if (m || h) {
            let seg: string;

            if (!m) {
                seg = '00';
            } else {
                if (h) {
                    seg = `${m}`.padStart(2, '0');
                } else {
                    seg = m.toString();
                }
            }

            output = `${seg}:${output}`;
        }

        if (h) {
            output = `${h}:${output}`;
        }

        if (!m && !h) {
            output = `0:${output}`;
        }

        return output;
    } catch {
        return '0:00';
    }
}

export async function getTranscriptTracks(signal: AbortSignal): Promise<TranscriptTrackInfo[] | undefined> {
    try {
        const info = await getTranscriptTrackInfo(window, signal);
        return info?.tracks;
    } catch (e) {
        console.error(e);
        return undefined;
    }
}

export function selectTranscriptTrack(
    tracks: TranscriptTrackInfo[] | undefined,
    preferredLanguage?: string,
    autogenerated?: boolean,
    fallbackTrack?: TranscriptTrackInfo
): TranscriptTrackInfo | undefined {
    if (!tracks || tracks.length === 0) return undefined;
    const autoGeneratedTrack = tracks.find((track) => track.isAutoGenerated);

    if (preferredLanguage) {
        const normalizedPreferred = preferredLanguage.toLowerCase();
        const preferredPrimary = normalizedPreferred.split('-')[0];
        const exact = tracks.filter((track) => track.languageCode?.toLowerCase() === normalizedPreferred);
        const candidates = exact.length
            ? exact
            : tracks.filter((track) => track.languageCode?.toLowerCase().split('-')[0] === preferredPrimary);
        if (candidates.length) {
            // Prefer the requested kind: asr when asked for auto-generated, manual otherwise
            const wantAuto = autogenerated === true;
            return candidates.find((track) => Boolean(track.isAutoGenerated) === wantAuto) ?? candidates[0];
        }
    }

    if (autogenerated === true && !preferredLanguage) {
        return fallbackTrack?.isAutoGenerated ? fallbackTrack : autoGeneratedTrack;
    }

    if (fallbackTrack) {
        return fallbackTrack;
    }

    const englishTrack = tracks.find((track) => track.languageCode?.toLowerCase().startsWith('en'));
    if (englishTrack) return englishTrack;

    if (autoGeneratedTrack) return autoGeneratedTrack;

    return tracks[0];
}

async function fetchTranscriptFromTimedText(baseUrl: string, signal: AbortSignal): Promise<TranscriptData | undefined> {
    // Generate authorization header for timedtext request
    const authHeader = buildSapSidAuthorizationHeader({ context: window });
    const headers: Record<string, string> = {};
    if (authHeader) {
        headers.authorization = authHeader;
    }

    const viaTimedText = await fetch(baseUrl, {
        method: 'GET',
        mode: 'cors' as RequestMode,
        credentials: 'include',
        headers,
        signal,
        cache: 'no-store'
    } as RequestInit);
    const text = await viaTimedText.text();
    return buildTranscriptFromTimedText(text) as TranscriptData | undefined;
}

function hasCueGroups(data: TranscriptData | undefined): boolean {
    return Boolean(
        wrapTryCatch(
            () =>
                data?.actions?.[0]?.updateEngagementPanelAction?.content?.transcriptRenderer?.body
                    ?.transcriptBodyRenderer?.cueGroups?.length
        )
    );
}

function encodeVarint(value: number): number[] {
    const out: number[] = [];
    let n = value;
    while (n > 127) {
        out.push((n & 127) | 128);
        n >>>= 7;
    }
    out.push(n);
    return out;
}

function encodeLengthDelimited(fieldNumber: number, bytes: number[]): number[] {
    return [...encodeVarint((fieldNumber << 3) | 2), ...encodeVarint(bytes.length), ...bytes];
}

/**
 * get_panel transcript params: base64(protobuf field 149 { 1: videoId, 3: 1 }).
 */
export function buildGetPanelTranscriptParams(videoId: string): string {
    const inner = [...encodeLengthDelimited(1, Array.from(new TextEncoder().encode(videoId))), (3 << 3) | 0, 1];
    return btoa(String.fromCharCode(...encodeLengthDelimited(149, inner)));
}

function parseTimestampSec(timestamp: string): number {
    return timestamp.split(':').reduce((acc, part) => acc * 60 + (Number(part) || 0), 0);
}

/**
 * Convert a get_panel (PAmodern_transcript_view) response into TranscriptData.
 * Sections are one per chapter; chapter-title items are skipped. Segments carry no
 * duration, so it is derived from the next segment's start (last: videoLengthSec - start, or 0).
 */
export function parseGetPanelTranscript(json: any, videoLengthSec?: number): TranscriptData | undefined {
    const sections: any[] | undefined =
        json?.content?.engagementPanelSectionListRenderer?.content?.sectionListRenderer?.contents;
    if (!Array.isArray(sections) || sections.length === 0) return undefined;

    const segments = sections
        .flatMap((section) => section?.itemSectionRenderer?.contents ?? [])
        .map((item) => item?.macroMarkersPanelItemViewModel)
        .filter((marker) => marker?.item?.timelineItemViewModel)
        .map((marker) => {
            const timeline = marker.item.timelineItemViewModel;
            const segment = timeline.contentItems?.[0]?.transcriptSegmentViewModel;
            const startSec: number =
                marker.onTap?.innertubeCommand?.watchEndpoint?.startTimeSeconds ??
                parseTimestampSec(timeline.timestamp ?? segment?.timestamp ?? '0');
            return { startSec, text: (segment?.simpleText as string | undefined) ?? '' };
        });
    if (segments.length === 0) return undefined;

    const cueGroups: TranscriptCueGroup[] = segments.map(({ startSec, text }, i) => {
        const nextSec = segments[i + 1]?.startSec ?? videoLengthSec;
        const durationSec = nextSec !== undefined && Number.isFinite(nextSec) ? Math.max(0, nextSec - startSec) : 0;
        return {
            transcriptCueGroupRenderer: {
                formattedStartOffset: { simpleText: toFormatted(startSec) },
                cues: [
                    {
                        transcriptCueRenderer: {
                            startOffsetMs: startSec * 1000,
                            durationMs: durationSec * 1000,
                            cue: { simpleText: text }
                        }
                    }
                ]
            }
        };
    });

    return {
        actions: [
            {
                updateEngagementPanelAction: {
                    content: { transcriptRenderer: { body: { transcriptBodyRenderer: { cueGroups } } } }
                }
            }
        ]
    };
}

function getPlayingVideoLengthSec(videoId: string): number | undefined {
    const player = document.getElementById('movie_player') as any;
    if (player?.getVideoData?.()?.video_id !== videoId) return undefined;
    const duration = (player.querySelector('video') as HTMLVideoElement | null)?.duration;
    return duration !== undefined && Number.isFinite(duration) ? duration : undefined;
}

async function fetchTranscriptViaGetPanel(
    videoId: string,
    languageCode: string | undefined,
    signal: AbortSignal
): Promise<TranscriptData | undefined> {
    try {
        const pageCfgData = await getPageCfgData(window, signal);
        const ytcfgClient = pageCfgData?.INNERTUBE_CONTEXT?.client as Record<string, unknown> | undefined;
        const client = {
            clientName: WEB_CLIENT_FALLBACK.clientName,
            clientVersion: pageCfgData?.INNERTUBE_CONTEXT_CLIENT_VERSION || WEB_CLIENT_FALLBACK.clientVersion,
            hl: languageCode || (pageCfgData?.HL as string) || window.navigator?.language || 'en',
            gl: (pageCfgData?.GL as string) || (ytcfgClient?.gl as string) || 'US'
        };
        const res = await fetch('https://www.youtube.com/youtubei/v1/get_panel?prettyPrint=false', {
            method: 'POST',
            mode: 'cors' as RequestMode,
            credentials: 'include',
            headers: { 'content-type': 'application/json' },
            signal,
            cache: 'no-store',
            body: JSON.stringify({
                context: { client },
                panelId: 'PAmodern_transcript_view',
                params: buildGetPanelTranscriptParams(videoId)
            })
        } as RequestInit);
        if (!res.ok) return undefined;
        return parseGetPanelTranscript(await res.json(), getPlayingVideoLengthSec(videoId));
    } catch (e: unknown) {
        if (e instanceof DOMException && e.name === 'AbortError') throw e;
        console.error('get_panel transcript fallback failed', e);
        return undefined;
    }
}

export async function getTranscriptVideo(
    signal: AbortSignal,
    options?: { languageCode?: string; autogenerated?: boolean }
): Promise<TranscriptData | undefined> {
    try {
        const info = await getTranscriptTrackInfo(window, signal);
        const tracks: TranscriptTrackInfo[] = info?.tracks ?? [];
        const selectedTrack = selectTranscriptTrack(
            tracks,
            options?.languageCode,
            options?.autogenerated,
            info?.defaultTrack
        );
        const trackBaseUrl = selectedTrack?.baseUrl?.replace('&fmt=srv3', '') || undefined;

        if (trackBaseUrl) {
            try {
                const built = await fetchTranscriptFromTimedText(trackBaseUrl, signal);
                if (hasCueGroups(built)) {
                    return built;
                }
            } catch (err) {
                console.error('direct timedtext fallback failed', err);
            }

            const pot = getTranscriptPot();
            if (pot && trackBaseUrl) {
                try {
                    // Generate authorization header for timedtext request with pot
                    const authHeader = buildSapSidAuthorizationHeader({ context: window });
                    const headers: Record<string, string> = {};
                    if (authHeader) {
                        headers.authorization = authHeader;
                    }

                    const viaTimedText = await fetch(`${trackBaseUrl}&potc=1&pot=${pot}&c=WEB`, {
                        method: 'GET',
                        mode: 'cors' as RequestMode,
                        credentials: 'include',
                        headers,
                        signal,
                        cache: 'no-store'
                    } as RequestInit);
                    const text = await viaTimedText.text();
                    const built = buildTranscriptFromTimedText(text) as TranscriptData | undefined;
                    if (hasCueGroups(built)) return built;
                } catch (err) {
                    console.error('timedtext with pot failed', err);
                }
            }
        }

        // Last resort: native transcript panel (paragraph-merged, second precision)
        const videoId = getVideoId(window.location.href);
        if (videoId) {
            return await fetchTranscriptViaGetPanel(videoId, options?.languageCode, signal);
        }
    } catch (e) {
        console.error(e);
        return undefined;
    }

    return undefined;
}
