import assert from 'node:assert';
import test from 'node:test';

import { resolveDefaultTranscriptTrack, selectTranscriptTrack } from '../src/source/utils/innertube/transcript';
import type { TranscriptTrackInfo } from '../src/source/utils/interfaces/i_types';

const asr = (languageCode: string): TranscriptTrackInfo => ({
    languageCode,
    isAutoGenerated: true,
    kind: 'asr',
    vssId: `a.${languageCode}`
});
const manual = (languageCode: string): TranscriptTrackInfo => ({
    languageCode,
    isAutoGenerated: false,
    vssId: `.${languageCode}`
});

// Mirrors jt508VjX2H8: every track is asr, original audio is en
const multiAsrTracks = [asr('ar'), asr('bn'), asr('nl'), asr('en'), asr('fr')];
// Mirrors YuOjMdevW0Q: manual tracks plus a ja asr sharing a code with ja manual
const mixedTracks = [manual('en'), manual('ja'), manual('zh-Hant'), asr('ja')];

test('selectTranscriptTrack: auto-generated pick honors the chosen language', () => {
    assert.strictEqual(selectTranscriptTrack(multiAsrTracks, 'en', true)?.languageCode, 'en');
});

test('selectTranscriptTrack: options default language without kind picks that language', () => {
    assert.strictEqual(selectTranscriptTrack(multiAsrTracks, 'en', undefined, multiAsrTracks[0])?.languageCode, 'en');
});

test('selectTranscriptTrack: same-code manual and asr tracks pick the requested kind', () => {
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'ja', false), mixedTracks[1]);
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'ja', true), mixedTracks[3]);
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'ja', undefined), mixedTracks[1]);
});

test('selectTranscriptTrack: falls back to primary subtag when no exact code', () => {
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'en-US')?.languageCode, 'en');
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'zh-hant')?.languageCode, 'zh-Hant');
});

test('selectTranscriptTrack: auto without language keeps an asr fallback track, else first asr', () => {
    assert.strictEqual(selectTranscriptTrack(multiAsrTracks, undefined, true, multiAsrTracks[3]), multiAsrTracks[3]);
    assert.strictEqual(selectTranscriptTrack(mixedTracks, undefined, true, mixedTracks[2]), mixedTracks[3]);
});

test('selectTranscriptTrack: unknown language falls back to default track', () => {
    assert.strictEqual(selectTranscriptTrack(mixedTracks, 'xx', false, mixedTracks[2]), mixedTracks[2]);
    assert.strictEqual(selectTranscriptTrack([], 'en'), undefined);
});

const toCaption = (track: TranscriptTrackInfo) => ({
    languageCode: track.languageCode,
    vssId: track.vssId,
    kind: track.isAutoGenerated ? 'asr' : undefined
});

test('resolveDefaultTranscriptTrack: uses default audio track captionTrackIndices[0] when no default index', () => {
    const captions = {
        captionTracks: multiAsrTracks.map(toCaption),
        audioTracks: [{ captionTrackIndices: [0, 1] }, { captionTrackIndices: [3, 0, 1, 2, 4] }],
        defaultAudioTrackIndex: 1
    };
    assert.strictEqual(resolveDefaultTranscriptTrack(captions, multiAsrTracks)?.languageCode, 'en');
});

test('resolveDefaultTranscriptTrack: matches by vssId when manual and asr share a code', () => {
    const captions = { captionTracks: mixedTracks.map(toCaption), defaultCaptionTrackIndex: 3 };
    assert.strictEqual(resolveDefaultTranscriptTrack(captions, mixedTracks), mixedTracks[3]);
});

test('resolveDefaultTranscriptTrack: root index wins over audio track defaults', () => {
    const captions = {
        captionTracks: mixedTracks.map(toCaption),
        defaultCaptionTrackIndex: 2,
        audioTracks: [{ defaultCaptionTrackIndex: 0, captionTrackIndices: [1] }],
        defaultAudioTrackIndex: 0
    };
    assert.strictEqual(resolveDefaultTranscriptTrack(captions, mixedTracks), mixedTracks[2]);
});

test('resolveDefaultTranscriptTrack: audio defaultCaptionTrackIndex wins over captionTrackIndices', () => {
    const captions = {
        captionTracks: mixedTracks.map(toCaption),
        audioTracks: [{ defaultCaptionTrackIndex: 0, captionTrackIndices: [1] }],
        defaultAudioTrackIndex: 0
    };
    assert.strictEqual(resolveDefaultTranscriptTrack(captions, mixedTracks), mixedTracks[0]);
});

test('resolveDefaultTranscriptTrack: falls back to languageCode without vssId, then tracks[0]', () => {
    const captions = { captionTracks: [{ languageCode: 'zh-Hant' }], defaultCaptionTrackIndex: 0 };
    assert.strictEqual(resolveDefaultTranscriptTrack(captions, mixedTracks), mixedTracks[2]);
    assert.strictEqual(resolveDefaultTranscriptTrack({ captionTracks: [] }, mixedTracks), mixedTracks[0]);
    assert.strictEqual(resolveDefaultTranscriptTrack(undefined, []), undefined);
});
