import { strict as assert } from 'node:assert';
import test from 'node:test';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
(globalThis as any).document = dom.window.document;
(globalThis as any).window = dom.window;
(globalThis as any).HTMLElement = dom.window.HTMLElement;
(globalThis as any).Element = dom.window.Element;
(globalThis as any).Node = dom.window.Node;

import * as stateModule from '../src/source/web-resources/state';
import { createTranscriptLoader } from '../src/source/web-resources/features/transcriptLoader';
import type { TranscriptLoaderDeps } from '../src/source/web-resources/features/transcriptLoader';
import type { WebResourcesState } from '../src/source/web-resources/state';
import type { TranscriptTrackInfo } from '../src/source/utils/interfaces/i_types';

const {
    createState,
    getSelectedTranscriptLanguage,
    setSelectedTranscriptLanguage,
    setDefaultTranscriptLanguage,
    getEffectiveTranscriptLanguage
} = stateModule;

const TRACKS: TranscriptTrackInfo[] = [
    { languageCode: 'en', displayName: 'English', isAutoGenerated: true },
    { languageCode: 'fr', displayName: 'French', isAutoGenerated: true },
    { languageCode: 'ko', displayName: 'Korean', isAutoGenerated: true }
] as TranscriptTrackInfo[];

const SAME_CODE_TRACKS: TranscriptTrackInfo[] = [
    { languageCode: 'ja', displayName: 'Japanese', isAutoGenerated: false },
    { languageCode: 'ja', displayName: 'Japanese', isAutoGenerated: true }
] as TranscriptTrackInfo[];

function setup(optionsDefault?: string, tracks: TranscriptTrackInfo[] = TRACKS) {
    let state: WebResourcesState = setDefaultTranscriptLanguage(createState(), optionsDefault);
    const menu = document.createElement('div');
    const loadButton = document.createElement('button');
    const loads: Array<{ languageCode?: string; autogenerated?: boolean }> = [];
    const deps = {
        state: {
            ...stateModule,
            getStateTranscriptTracks: stateModule.getTranscriptTracks,
            getState: () => state,
            setState: (next: WebResourcesState) => {
                state = next;
            }
        },
        elements: {
            elLiveApp: document.createElement('div'),
            elLoadTranscriptVideo: loadButton,
            elTranscriptLangButton: null,
            elTranscriptLangMenu: menu
        },
        callbacks: {
            updateTitleCount: () => {},
            showLoadComments: () => {},
            closeAllDropdowns: () => {},
            setMenuVisibility: () => {}
        }
    } as unknown as TranscriptLoaderDeps;
    const loader = createTranscriptLoader(deps);
    loader.load = async (_trigger, languageCode, autogenerated) => {
        loads.push({ languageCode, autogenerated });
    };
    const render = () => loader.renderLanguageMenu(tracks, getSelectedTranscriptLanguage(state));
    const items = () => Array.from(menu.querySelectorAll<HTMLElement>('.ycs_dropdown_item'));
    const activeLabels = () =>
        items()
            .filter((el) => el.classList.contains('ycs_dropdown_item--active'))
            .map((el) => el.textContent);
    const click = (substring: string) => {
        const item = items().find((el) => el.textContent?.includes(substring));
        assert.ok(item, `menu item ${substring} not found`);
        item.click();
        render();
    };
    return { getState: () => state, loads, loadButton, render, activeLabels, click };
}

test('effective transcript language: session pick, else options default, else undefined', () => {
    const base = createState();
    assert.equal(getEffectiveTranscriptLanguage(base), undefined);
    const withDefault = setDefaultTranscriptLanguage(base, 'fr');
    assert.deepEqual(getEffectiveTranscriptLanguage(withDefault), { languageCode: 'fr' });
    const picked = setSelectedTranscriptLanguage(withDefault, { languageCode: 'ko', autogenerated: true });
    assert.deepEqual(getEffectiveTranscriptLanguage(picked), { languageCode: 'ko', autogenerated: true });
    assert.deepEqual(getEffectiveTranscriptLanguage(setSelectedTranscriptLanguage(picked, undefined)), {
        languageCode: 'fr'
    });
});

test('Default item clears the session pick and loads YouTube default when options default is empty', () => {
    const t = setup(undefined);
    t.render();
    assert.deepEqual(t.activeLabels(), ['Default (YouTube / options)']);

    t.click('[ko]');
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ko', autogenerated: true });
    assert.deepEqual(t.activeLabels(), ['Korean (auto) [ko]']);

    t.click('Default');
    assert.equal(getSelectedTranscriptLanguage(t.getState()), undefined);
    assert.deepEqual(t.loads.at(-1), { languageCode: undefined, autogenerated: undefined });
    assert.deepEqual(t.activeLabels(), ['Default (YouTube / options)']);

    t.loadButton.click();
    assert.deepEqual(t.loads.at(-1), { languageCode: undefined, autogenerated: undefined });
});

test('Default item falls back to options default and stays the only active item', () => {
    const t = setup('fr');
    t.render();
    assert.deepEqual(t.activeLabels(), ['Default (YouTube / options)']);

    t.loadButton.click();
    assert.equal(t.loads.at(-1)?.languageCode, 'fr');

    t.click('[ko]');
    assert.deepEqual(t.activeLabels(), ['Korean (auto) [ko]']);
    t.loadButton.click();
    assert.equal(t.loads.at(-1)?.languageCode, 'ko');

    t.click('Default');
    assert.deepEqual(t.activeLabels(), ['Default (YouTube / options)']);
    assert.deepEqual(getEffectiveTranscriptLanguage(t.getState()), { languageCode: 'fr' });
    t.loadButton.click();
    assert.equal(t.loads.at(-1)?.languageCode, 'fr');

    t.click('[fr]');
    assert.deepEqual(t.activeLabels(), ['French (auto) [fr]']);
});

test('manual and auto tracks with the same language code are selected and highlighted independently', () => {
    const t = setup(undefined, SAME_CODE_TRACKS);
    t.render();

    t.click('Japanese (auto) [ja]');
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: true });
    assert.deepEqual(t.activeLabels(), ['Japanese (auto) [ja]']);

    t.click('Japanese [ja]');
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: false });
    assert.deepEqual(t.activeLabels(), ['Japanese [ja]']);
});

test('Load button keeps the picked track kind', () => {
    const t = setup('ja', SAME_CODE_TRACKS);
    t.render();

    t.loadButton.click();
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: undefined });

    t.click('Japanese (auto) [ja]');
    t.loadButton.click();
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: true });

    t.click('Japanese [ja]');
    t.loadButton.click();
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: false });

    t.click('Default');
    assert.deepEqual(t.activeLabels(), ['Default (YouTube / options)']);
    t.loadButton.click();
    assert.deepEqual(t.loads.at(-1), { languageCode: 'ja', autogenerated: undefined });
});
